name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: '14'
        cache: 'npm'
    - name: NPM Install
      run: npm i
    - name: Deploy
      run: npx workers-ci deploy src/index.js vat
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}